# Generated by Django 4.0b1 on 2021-11-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itempreview',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default='default', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
