# Generated by Django 4.0b1 on 2021-12-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_itempreview_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('parent', models.CharField(blank=True, max_length=200)),
                ('image', models.FileField(upload_to='pictures')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='cat',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
